### PR TITLE
When loading a map, enforce a know data format. Refs #557 and #547.

### PR DESCRIPTION
**Pull request by s0undt3ch**
- Simplified some code logic.
- Any additional data defined on the map, overrides the profile data.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@techhat I just made your life harder.... :smiley: 

Here's lot's of goodies to review... again!

Before merging we need to review/discuss the `map_` settings used on maps.

**Comment by s0undt3ch** [comment]
What's included in last commit.
- We now merge the map provided configuration into the profile. Fixes #467. Fixes #554.
- This commit also fixes #547 and closes #557. We're simply handling the problem at an earlier stage.
- Since we changed how maps information is merged into the profile data, we need to revisit `map_minion`, `map_grains`, `map_volumes`, etc, since there's no need for the `map_` prefix anymore. ALL defined data in the map will be updated in the chosen profile.
- **ALL** cloud drivers should now return the `deploy_kwargs` since that information will be required when `make_master` is set to true. It will be ignored on the CLI code if the user does not pass `--show-deploy-args`.
- If `--no-deploy` is used and `make_master` is True, warn and fail as soon as possible, it would never work.
- Updated all cloud drivers to show their VM creation details.

**Comment by mafrosis** [comment]
@s0undt3ch looks like some stirling work you've done here

**Comment by s0undt3ch** [comment]
Some decisions still remain, do we keep `map_grains`, `map_minion`, etc, or, plain `grains`, `minion`, etc, like in the profiles, while providing backwards compatibility?

**Comment by mafrosis** [comment]
I did think about that one - but I'm not sure right now. If the only benefit is consistency, then we can always change the names later.

**Comment by s0undt3ch** [comment]
Well, yes, consistency.

But this consistency has a price, we either break backwards compatibility for those already using `map_minion`, etc, or deprecate it's usage with a warning for a few releases.

We should **not** support both for too long.

**Comment by mafrosis** [comment]
I'm don't think I'm familiar enough with the nuts and bolts of what's going on here to comment. There's been a lot of change lately that I'm still not up on...

**Comment by s0undt3ch** [comment]
Well, I'm asking because I've been slowly integrating into salt-cloud while you guys have been implementing features for it fir quite some time now.

Hence me breaking the maps ;)
And another thing you fixed which I can't remember now...

**Comment by s0undt3ch** [comment]
Given the following configuration:

``` yaml
minion:
  # The level of messages to send to the console.
  # One of 'garbage', 'trace', 'debug', info', 'warning', 'error', 'critical'.
  # Default: 'warning'
  log_level: debug

  # The level of messages to send to the log file.
  # One of 'garbage', 'trace', 'debug', info', 'warning', 'error', 'critical'.
  # Default: 'warning'
  log_level_logfile: trace
```

``` yaml
# /etc/salt/cloud.providers.d/ec2.conf

ec2-config:
  - id: XXXXXXXXXXXXXXXXXXXXXX
    key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    keyname: pedro-algarvio
    securitygroup: default
    private_key: /home/vampas/projects/salt/cloud/.config/ssh-keys/aws
    delvol_on_destroy: True
    rename_on_destroy: True
    provider: ec2
```

``` yaml
# /etc/salt/cloud.profiles.d/ec2.conf

Ubuntu-12.04-64bit:
  provider: ec2-config
  image: ami-0145d268
  size: Micro Instance
  ssh_username: ubuntu
  securitygroup:
    - default
```

``` yaml
# /etc/salt/cloud.map

Ubuntu-12.04-64bit:
  TT_Master:
    map_minion:
      retry_dns: 5
    map_grains:
      omelet: du fromage
    make_master: True
  TT2:
    map_minion:
      retry_dns: 5
    map_grains:
      omelet: du fromage
  TT3:
    map_minion:
      retry_dns: 5
    map_grains:
      omelet: du fromage
```

After the mapping data has been merged into the profile:

``` yaml
TT2:
  grains:
    omelet: du fromage
  image: ami-0145d268
  minion:
    retry_dns: 5
  name: TT2
  profile: Ubuntu-12.04-64bit
  provider: ec2-config
  securitygroup: &id001
  - default
  size: Micro Instance
  ssh_username: ubuntu
TT3:
  grains:
    omelet: du fromage
  image: ami-0145d268
  minion:
    retry_dns: 5
  name: TT3
  profile: Ubuntu-12.04-64bit
  provider: ec2-config
  securitygroup: *id001
  size: Micro Instance
  ssh_username: ubuntu
TT_Master:
  grains:
    omelet: du fromage
  image: ami-0145d268
  make_master: true
  minion:
    retry_dns: 5
  name: TT_Master
  profile: Ubuntu-12.04-64bit
  provider: ec2-config
  securitygroup: *id001
  size: Micro Instance
  ssh_username: ubuntu
```

Computed(merged) minion dict:

``` yaml
acceptance_wait_time: 10
autoload_dynamic_modules: true
backup_mode: ''
cache_jobs: false
cachedir: /var/cache/salt/minion
clean_dynamic_modules: true
conf_file: /etc/salt/minion
cython_enable: false
default_include: minion.d/*.conf
disable_modules: []
disable_returners: []
dns_check: true
environment: null
external_nodes: ''
failhard: false
file_client: remote
file_roots:
  base:
  - /srv/salt
grains:
  omelet: du fromage
hash_type: md5
id: TT_Master
ipc_mode: ipc
ipv6: false
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_file: /var/log/salt/minion
log_fmt_console: '[%(levelname)-8s] %(message)s'
log_fmt_logfile: '%(asctime)s,%(msecs)03.0f [%(name)-17s][%(levelname)-8s] %(message)s'
log_granular_levels: {}
log_level: debug
log_level_logfile: trace
loop_interval: 60
master: salt
master_finger: ''
master_port: '4506'
mine_interval: 60
module_dirs: []
multiprocessing: true
open_mode: false
outputter_dirs: []
permissive_pki_access: false
pidfile: /var/run/salt-minion.pid
pillar_roots:
  base:
  - /srv/pillar
pki_dir: /etc/salt/pki/minion
providers: {}
range_server: range:80
recon_max: 5000
render_dirs: []
renderer: yaml_jinja
retry_dns: 5
returner_dirs: []
root_dir: /
sls_list: []
sock_dir: /var/run/salt/minion
startup_states: ''
state_output: full
state_top: top.sls
state_verbose: true
states_dirs: []
tcp_keepalive: true
tcp_keepalive_cnt: -1
tcp_keepalive_idle: 300
tcp_keepalive_intvl: -1
tcp_pub_port: 4510
tcp_pull_port: 4511
test: false
top_file: ''
update_restart_services: []
update_url: false
user: root
verify_env: true
whitelist_modules: []
win_repo_cachefile: salt://win/repo/winrepo.p
```

I think this is a good example on how the data is manipulated internally.

**Comment by s0undt3ch** [comment]
This is now waiting for minion keys pre-seed on the master.

The good news is, it's almost implemented. Just needs some more testing. But now, :sleeping: ...

**Comment by s0undt3ch** [comment]
This PR is now ready to be reviewed once more. This time with minion keys pre-seeding support.

**Pull request merged**
