### PR TITLE
added libtool emerge in gentoo bootstrap

### PR DESCRIPTION
**Pull request by KennethWilke**
This fixes compilation issues with crypto++ on rackspace cloud servers

### CODE REVIEW

**Comment by KennethWilke** [comment]
testing this right now, plz don't merge yet ;)

**Comment by KennethWilke** [comment]
this is looking good on my end

**Comment by techhat** [comment]
I hate to turn away contributions @KennethWilke, but you'll want to make these changes upstream to the salt-bootstrap project: https://github.com/saltstack/salt-bootstrap . Then your changes will be pulled down here again upon release.

**Comment by KennethWilke** [comment]
Alrighty I can do that. if these files are referenced from another repo is it possible to include salt-bootstrap as a git submodule of this one?

**Comment by techhat** [comment]
@KennethWilke, we tried that. Short story, it caused a lot of pain. Longer story, it has to live in the same directory as a bunch of other scripts that do belong in this repo, and submodules have to be done as full directories, not individual files.

**Comment by s0undt3ch** [comment]
@KennethWilke Can't wait to get a pull request in [salt-boostrap](https://github.com/saltstack/salt-bootstrap) with this fix! :smile:

**Comment by KennethWilke** [comment]
Hey now! Let me at least get a cup of coffee first @s0undt3ch !

**Comment by KennethWilke** [comment]
@s0undt3ch request submitted! https://github.com/saltstack/salt-bootstrap/pull/204

**Comment by techhat** [comment]
You're awesome, @KennethWilke! Sorry for the runaround.

**Comment by s0undt3ch** [comment]
@KennethWilke cofee is overrated! ;) Thanks!!!

**Comment by s0undt3ch** [comment]
Opps! Closing again.

**Pull request closed without merging**
