### PR TITLE
Ability to deploy EBS volumes on ec2

### PR DESCRIPTION
**Pull request by maratsh**
Latest libcloud has support EBS management.
This commits is  just draft for volumes attaching support.

example:

```
test-micro:
    - test-temp-s02:
        volumes:
            - { size: 1, device: /dev/sdf}
            - { size: 1, device: /dev/sdh}
```

### CODE REVIEW

**Comment by techhat** [comment]
Hey @deutsche just a quick request before we do the merge:

Could you please add a docstring to the create_attach_volumes function? Also, line 255 in aws.py has tabs instead of spaces, and is kind of long. Would you mind reformatting it?

**Comment by maratsh** [comment]
it is ok now ?

**Comment by techhat** [comment]
Awesome, thanks man!

**Comment by techhat** [comment]
@deutsche, are you still using this? I'm not finding anything on how to use it in the docs, and I'm getting ready to do some work with it.

**Comment by maratsh** [comment]
@techhat i'm not using this just right now. You can use my little example in first topic for documentation. Codebase has great changes.  I see 3 modules for aws clouds, it is coool :+1:

**Pull request merged**
