### PR TITLE
Add direct avail_sizes function to ec2

### PR DESCRIPTION
**Pull request by techhat**
It should be noted that this also changes the format in which the data is returned from avail_sizes. However, it is much more accurate and informative than what we were returning before from libcloud.

### CODE REVIEW

**Comment by techhat** [comment]
@thatch45, could I get your opinion before we merge this?

**Comment by s0undt3ch** [comment]
The list cannot be computed at runtime? Using the direct API? You'd have to keep updating that list(dict) every time it changed...

**Comment by techhat** [comment]
This is exactly how libcloud does it:

https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/ec2.py

But I was very careful not to copy their code. Most of my research was based on the information in the URL I put in the docstrings, the rest was in trying to keep the return data look vaguely like how our AWS driver was already presenting it, but more complete.

**Comment by s0undt3ch** [comment]
If there's not way to get that information using EC2 api, then hardcoded is the way to go. (/me thinks)

**Comment by techhat** [comment]
I'm going to go ahead and merge this. If it ends up being the wrong direction, we can back it out.

**Pull request merged**
