### PR TITLE
initial package

### PR DESCRIPTION
**Pull request by ghost**
would you like a package? can be included in daily builds also.

### CODE REVIEW

**Comment by akoumjian** [comment]
Yes, please!

**Comment by techhat** [comment]
Awesome, this is good stuff!

**Comment by ghost** [comment]
there are salt-cloud 0.8.3 packages in the salt PPA for several ubuntu versions, and the install instructions would be identical for salt on ubuntu ( http://docs.saltstack.org/en/latest/topics/installation/ubuntu.html )

**Comment by thatch45** [comment]
W00t!!
Thanks @seanchannel! Hopefully this will help us get more adoption with salt-cloud!

**Pull request merged**
