### PR TITLE
CLI mods

### PR DESCRIPTION
**Pull request by mafrosis**
Previously we use exits all over to break the flow in the cli module. I believe this patch is a better solution!

Comments please.

Changes:
- correct exit codes on error
- refactored to use and if-else block, so we only exit on success in one place
- changed query option to be exclusive of other options; the same as others in the list (this the only functionality change; look at bbbd10c)

### CODE REVIEW

**Comment by techhat** [comment]
This is pretty intense. Let me take my time looking through this before I merge it.

**Comment by mafrosis** [comment]
No worries. I tried to break down the commits as far as was sensible, so it'll be easier to digest that way.

**Comment by techhat** [comment]
Actually, let me merge @s0undt3ch's first (#380), which is likely to cause a merge conflict. Keep posted.

**Comment by mafrosis** [comment]
Hehe yeah I saw that coming too. I'll rebase over here when you're ready.

**Comment by techhat** [comment]
Looks good, let's go with it.

**Pull request merged**
