### PR TITLE
universal repo setup

### PR DESCRIPTION
**Pull request by ghost**
These comments are included in the commit:
# add-apt-repository requires an additional dep and is in different packages
# on different systems. Although seemingly ubiquitous it is not a standard,
# and is only a convenience script intended to accomplish the below two steps
# doing it this way is universal across all debian and ubuntu systems.

### CODE REVIEW

**Comment by akoumjian** [comment]
So... what about the claim that this code was hanging on 12.04.1? I wasn't able to reproduce, but that was why it changed.

**Comment by inthecloud247** [comment]
yeah I don't know why this was reverted... if you check the history, this has now gone back and forth a few times.

**Comment by inthecloud247** [comment]
it'd be more compatible to just have a check for the release and use the proper deb package.

**Comment by akoumjian** [comment]
Considering that this is only supposed to be left here as legacy anyways, it seems like it should be keep the way it was before the first change. New users should be using bootstrap-script.

**Comment by inthecloud247** [comment]
well if it's only legacy then we shouldn't care about it breaking for ubuntu > 12.04 ?

bootstrap-script was broken the last I checked a few days ago...

**Comment by ghost** [comment]
please see gigantic comments in PR: https://github.com/saltstack/salt-cloud/issues/277

**Comment by techhat** [comment]
I'm going to agree with @akoumjian here... nobody should be using these scripts anymore; they are now intended for academic purposes only. Let's stop going back and forth on this, and focus on getting salt-bootstrap to resolve any remaining issues.

**Comment by ghost** [comment]
add-apt-repository's main purpose in life is to present the ubuntu user with nicely formatted prompts. It's a Canonical special and I highly recommend a more standard approach in salt-bootstrap as well.

**Comment by inthecloud247** [comment]
@techhat If that's the case, then just delete them all please. It's really confusing to have old unmaintained scripts here.

If they remain in the project, clearly they'll need to be maintained to ensure that they continue to work with the newer versions of salt-cloud.

**Comment by inthecloud247** [comment]
and @seanchannel, the point of the ubuntu.sh script is to install salt-cloud on ubuntu systems. debian systems should use the debian.sh script right? ubuntu is its own thing, and it's appropriate to treat it differently.

**Comment by techhat** [comment]
@ydavid365, I will not remove functionality just because it confuses you, whether or not I think others should be using it. A number of users will not switch to salt-bootstrap immediately, and pulling out the rug underneath them like that would be unacceptable.

@seanchannel is a core Salt dev and our Ubuntu maintainer. As far as I am concerned, his word on Ubuntu is gospel until otherwise proven. Neither he, nor @akoumjian seem to be able to reproduce your issue. If you can give exact steps that @seanchannel can use to reliably and predictably reproduce the situation that is causing you stress, I have no doubt that he will do what it takes to resolve the issue, even if it means reversing his own changes. "Sometimes it doesn't do what I expect" isn't helpful. As it stands, I am content to leave these files as they are.

**Comment by inthecloud247** [comment]
Here's the cloud.profiles entry on aws that was failing for me. Let me know if it works for you?

``` python
small_region:
  provider: aws
  image: ami-7e2da54e
  location: us-west-2
  availability_zone: us-west-2c
  size: Small Instance
  script: Ubuntu
```

**Pull request merged**
