### PR TITLE
Add support for userdata to OpenStack

### PR DESCRIPTION
**Pull request by pabelanger**
A simple patch to allow a user to pass userdata when a node is created
for OpenStack.

Signed-off-by: Paul Belanger paul.belanger@polybeacon.com

### CODE REVIEW

**Comment by pabelanger** [comment]
The more I think about this, I think it should support both inline syntax or reading an external file.

**Comment by pabelanger** [comment]
Decided to change it to an external file, it should give the user more options.

**Comment by techhat** [comment]
@pabelanger what is the file format like for the included file? Is it based on an existing format from openstack?

**Comment by pabelanger** [comment]
@techhat I'd say the format should be per http://cloudinit.readthedocs.org/en/latest/ however, it really depends on what is reading the data.  The choice is really up to the user.

**Comment by techhat** [comment]
@pabelanger looks good, thanks!

**Pull request merged**
