### PR TITLE
Option to disable output from SSH deploy script

### PR DESCRIPTION
**Pull request by mafrosis**
I changed from subprocess.call to using the communicate function. This should ensure that we consume the output from the SSH connection, but we don't actually need to print it on stdout.

### CODE REVIEW

**Comment by techhat** [comment]
Testing this on a local branch, I was still able to see the SSH output of the deploy script, using the following profile:

``` yaml
ec2-ubuntu:
    provider: ec2
    image: ami-3d4ff254
    size: Micro Instance
    script: bootstrap-salt
    ssh_username: ubuntu
    delvol_on_destroy: True
    display_ssh_output: False
```

Did I misunderstand the usage?

**Comment by techhat** [comment]
My apologies, I was confusing `__opts__` with `vm_`. This is working fine, when I move the option into the main cloud config, which is what makes sense with trying to spin up instances in parallel.

I'm going to go ahead and merge this, but could you please add usage documentation to the doc/ directory?

**Comment by mafrosis** [comment]
Nice! Honestly, I didn't know if this would be accepted.. Since it now has, I'll write the docs entry.

**Comment by techhat** [comment]
You're not the first person to mention how noisy the output is, so I'm going to assume it's a feature other people may want. And I'm not going to go all Gnomish on you and start pulling out feature you use, just because they don't suit my own needs. So yeah, I'm okay with accepting it. ^_^

**Comment by mafrosis** [comment]
Well nobody likes a load of uncontrollable noise being dumped on stdout right? I was thinking that maybe log level debug should auto display_ssh_output to true. What do you think?

**Comment by techhat** [comment]
I always watch the output from SSH, but uncontrollable output is another thing. And I would be hesitant to auto-set that option, since I always use debug mode, and may have a need to turn off SSH output.

**Pull request merged**
