### PR TITLE
Add rename to aws

### PR DESCRIPTION
**Pull request by techhat**
Resolves issue #273.

### CODE REVIEW

**Comment by mafrosis** [comment]
How come it's `kwargs['newname']` and not just `newname`?

Please tell me to sssh if I'm just second guessing something that should be obvious ;0

**Comment by techhat** [comment]
Imagine the following command:

```
salt-cloud -a rename name1 name2
```

In this instance, it would attempt to run the rename action against a machine named name1, and then a machine named name2... and it would fail, because it wouldn't know what the new name was for either.

With today's additions, if --action detects an argument with '=' in it, it turns it into a kwarg. And if it detects kwargs, it passes them through to the resulting action.

**Comment by mafrosis** [comment]
Yeah.. I missed the implications of 8301e09 earlier. I'll just be quiet now.

**Comment by techhat** [comment]
No worries, it's not obvious, and I bet you won't be the last person to question it.

**Comment by mafrosis** [comment]
It's probably worth adding a usage line in the comment to that method. And maybe we should add a check to prevent people spinning up new nodes with an equals sign in their name. Like I just did.

**Comment by techhat** [comment]
Good call. Let me add that to this pull req.

**Comment by techhat** [comment]
Done.

**Pull request merged**
