### PR TITLE
update script name

### PR DESCRIPTION
**Pull request by ghost**
yar! ya best be updatin' this one, too! "bootstrap-salt-minion" was recently renamed to several variants.

### CODE REVIEW

**Comment by techhat** [comment]
I knew they were planning on renaming, though I haven't looked yet. However, I don't think wget is a good default, since it can rarely be expected to be there on a new system. Plus, official salt-cloud releases will contain a full copy of the actual bootstrap script.

**Comment by ghost** [comment]
As it stands now it's broken; no deploy script gets called at all due to the default being one that doesn't exist. perhaps the default in config.py needs to point at something that exists and works now, but can be changed later, like "default.sh", "bootstrap-generic", etc.

**Comment by techhat** [comment]
To be fair, it also didn't work straight out of git before the name change either. We only bundle the script with the release tarball.

The problem with making anything else the default is that they rely on other components that can't be expected to be on the system already. Neither curl nor wget is standard across the board (and are almost never installed by default), and even Python can't be expected to be installed in FreeBSD, which we also have active users in.

So as long as you install from the release tarball (via PyPi or one of the community packages), you'll be fine, because the bootstrap script is there, and by design needs no other components. We could, however, put together a doc that discusses running an instance from a git checkout.

**Comment by ghost** [comment]
So there is an as-yet-unwritten script that is not yet included?  Something that exists has to be the default. I understand if there is another script pending, but it looks like bootstrap has been added already. This seems intentionally left broken for reasons I do not fathom.

**Comment by techhat** [comment]
But... something that exists in the release tarball is the default. It's not pending or anything, we just include the latest stable of salt-bootstrap when we cut a release.

**Comment by ghost** [comment]
It would be helpful to have that "latest stable" version committed in salt-cloud. Anyone using git will need to know how to deal with this.

**Comment by inthecloud247** [comment]
What about including salt-bootstrap as a git submodule?

**Pull request closed without merging**
