### PR TITLE
Use cElementTree if available

### PR DESCRIPTION
**Pull request by holmboe**
Same code as used in Salt.

### CODE REVIEW

**Comment by techhat** [comment]
Thanks @holmboe. I'm going to hold off on this for two reasons. First, I've been lazy about converting this to use the same function that I built into salt:

https://github.com/saltstack/salt/blob/develop/salt/utils/xmlutil.py

Second, we're planning to merge salt-cloud into salt in the next couple of weeks, and at that point it can take advantage of salt's Python. compatibility layer.

**Comment by s0undt3ch** [comment]
And salt-cloud depends on salt so we can import from salt's `_compat`, no?

**Comment by techhat** [comment]
Agreed.

**Comment by holmboe** [comment]
Ah, no stress. I had picked up on the planned/proposed salt-cloud -> salt merge in a comment somewhere so I had that in mind actually.

**Comment by techhat** [comment]
Thanks for the pull, and for being so understanding, @holmboe!

**Comment by holmboe** [comment]
:thumbsup:

**Pull request merged**
