### PR TITLE
Let's use salt's non blocking `popen`.

### PR DESCRIPTION
**Pull request by s0undt3ch**
Since salt is reusing salt-cloud's non blocking `popen` and since we depend on salt, let's depend on salt's non blocking `popen`.

Let's wait for saltstack/salt#5803 to be merged before merging this.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Did you read it all? :smiley:

**Comment by techhat** [comment]
There wasn't much to read... did I miss something obvious?

**Comment by s0undt3ch** [comment]
Let's wait for saltstack/salt#5803 to be merged before merging this.

**Comment by s0undt3ch** [comment]
:)

**Pull request merged**
