### PR TITLE
Fixing small issue in DescribeInstances result handler

### PR DESCRIPTION
**Pull request by abemusic**
Attempting to reference the `error` key in an empty list.

### CODE REVIEW

**Comment by techhat** [comment]
Is the list always empty? If there is sometimes an error in there, I would like to see it. Can we instead do something like:

```
err_msg = ''
if 'error' in data:
    err_msg = data['error']
```

**Comment by abemusic** [comment]
As the code was written, it was testing for an instance of a list and that the list was empty. In that case `data['error']` would always throw:

``` bash
TypeError: list indices must be integers, not str
```

I'm not sure why the query result would be an empty list though.

**Comment by techhat** [comment]
Sorry, I should have looked closer before opening my big mouth. You are correct.

**Comment by abemusic** [comment]
@techhat No worreis...I had to take a second look myself to make sure I wasn't doing something silly :-D

**Pull request merged**
