### PR TITLE
Termination protection enhancement

### PR DESCRIPTION
**Pull request by mafrosis**
I'm not sure if we want to merge this just yet, but I opened this pull req for discussion.

Added support for toggling termination protection using the botocore lib which is now [0.5.1 in Pypi](http://pypi.python.org/pypi/botocore/0.5.1).

Also wrapped the core libcloudfuncs.destroy() method to gracefully handle the exception raised in libcloud when termination protection is switched on for a node.

### CODE REVIEW

**Comment by techhat** [comment]
I'm pretty excited about the idea of using botocore. I'm not sure about the late import on this. Maybe we can just doc that botocore is only needed to be installed for advanced actions? Perhaps @thatch45 can chime in when he gets a chance.

**Comment by mafrosis** [comment]
There's a number of things in there that I'm not too sure about - the late import being one of them.

I was thinking that some advanced features would rely on botocore - then when libcloud catches up, we can port the code to use that. We don't want to add a dependency on botocore (since it's only for AWS) but the people who use AWS will almost certainly want the extra features provided by boto...

**Comment by techhat** [comment]
@mafrosis, you'll want to take a look at this again... it looks like whatever changes have been applied since we first started looking at it have made it unmergeable (is that a word?).

**Comment by mafrosis** [comment]
Yeah I'll need to rebase the code periodically since there's a lot happening in the aws module right now.

The question is still around how we're going to work with botocore.. If people are happy to `pip install` in the short term, then this can be merged..

**Comment by techhat** [comment]
Is there anything that libcloud does that botocore doesn't do? I'm not opposed to switching the AWS module entirely over to botocore, if it's a better solution.

**Comment by mafrosis** [comment]
I'm certain everything _can_ be done by boto (or will be in the near future) - however porting the AWS will be a bit of work. The salt-cloud config is tightly coupled to the params passed to libcloud and that will all need resolving.

Start small with just the functions missing from libcloud?

**Comment by techhat** [comment]
Sounds like a plan. But maybe before we do that, we should fill in the rest of what libcloud has that we're not using, so we know what needs to be filled in.

**Comment by mafrosis** [comment]
How about a policy of "use libcloud if possible, else use botocore". At least until we have botocore in apt/yum and we can port the whole module.

**Comment by techhat** [comment]
Sold.

**Comment by techhat** [comment]
This is good, and it looks like it can be merged again... but it's missing the new "delete_sshkeys" option that I added to libcloudfuncs yesterday in #324. Would you mind adding that before I merge this?

**Comment by mafrosis** [comment]
Updated to latest develop HEAD

**Comment by techhat** [comment]
Nice to finally be able to merge this!

**Comment by mafrosis** [comment]
Agreed! Since 0.13.0 has just dropped, is it time to roll another salt-cloud release? (Or has that happened when I wasn't watching?)

**Comment by techhat** [comment]
The time has come (especially with the config breakage between salt 0.13.0 and salt-cloud <= 0.8.4). I'll be cutting a release this week.

**Comment by mafrosis** [comment]
I've just been reviewing the code we just merged, and I have a couple of comments/changes. Sorry I didn't do this earlier!
- All EC2 calls in botocore use the node's "instanceId". This is only available through salt when the "ec2_info" grain is available.. Which complicates things greatly.
- We still have the late import. This should be changed.
- I added usage examples to the new methods.

**Comment by techhat** [comment]
Well, let's get another pull req open, and we'll get 'em merged. Thanks for all the work, @mafrosis!

**Pull request merged**
