### PR TITLE
Add support for OpenStack floating IPs

### PR DESCRIPTION
**Pull request by pabelanger**
This attempts to fix #637 and fix #791. However, this code currently
depends on libcloud 0.14.0-dev, which has not been released yet.  I have
updated the requirements for tox to handle the development release of
libcloud however I don't expect it to get merged.

So, for now, this is just a public patch for people to test out.  I'll
revist the commit message once the next release of libcloud is out.

Signed-off-by: Paul Belanger paul.belanger@polybeacon.com

### CODE REVIEW

**Comment by techhat** [comment]
The changes to requirements.txt are not going to fly. Libcloud is required all over salt-cloud, and cannot be removed from requirements.txt. netaddr is only used in openstack, and should not be in requirements.txt.

Still looking at the rest of the changes.

**Comment by pabelanger** [comment]
libcloud is still a requirement, I have just bumped it to 0.14.0-dev.  For this patch to work, 0.14.0 will have to be the minimum requirement.  I am trying to find out when the next release will be.

As for netaddr, I believe it needs to be in requirements, since salt-cloud uses it.  I can move that into a separate patch.

The other changes are to ignore_cidr, that code was a mess and I cannot see how it ever worked.

**Comment by techhat** [comment]
Some of the cloud modules have requirements that only apply to them; softlayer and softlayer-hw require the SoftLayer package. The legacy aws driver required botocore. And the openstack driver is the only thing that requires netaddr. Just like in Salt proper, we don't add packages to requirements.txt that are only required by one module; among other reasons, it places undue stress on our community packagers (we learned that the hard way with botocore). That being the case, netaddr doesn't go into requirements.txt.

**Comment by pabelanger** [comment]
Okay, I guess there is a difference on how you guys use the requirements file, in the past any dependency that an application needed to running correctly would be placed their [1]. However, I can move it into test-requirements.txt because it will be needed if unit tests will be needed.

Additionally, if you want to keep separate requirements for setup.py and tox, that can be done too.  However, will just lead to duplicate pip install files.

[1] http://www.pip-installer.org/en/latest/cookbook.html#requirements-files

**Pull request merged**
