### PR TITLE
Show helpful error when a bad aws location is used

### PR DESCRIPTION
**Pull request by techhat**
Seriously, I wasted too much time because this was missing.

### CODE REVIEW

**Comment by akoumjian** [comment]
I know it's a tiny change, but don't we normally want someone other then the author to merge the pull request?

**Comment by thatch45** [comment]
It is ok if the author merges small changes.

**Comment by akoumjian** [comment]
That's fair.

**Comment by techhat** [comment]
Normally, I would agree... but as Tom said, it was a tiny change.

**Comment by thatch45** [comment]
You are right though, and for the vast majority of them they should be reviewed

**Pull request merged**
