### PR TITLE
Report syntax errors in map file. Exit when nothing to do for a map.

### PR DESCRIPTION
**Pull request by mafrosis**
As described, just a couple of small fixes relating to map files.

You may well want to change the "Nothing to do" message!

### CODE REVIEW

**Comment by techhat** [comment]
@mafrosis, you'll want to do a git fetch and redo this commit.

**Comment by mafrosis** [comment]
@techhat snap.. someone merged whilst I was committing!

I've fixed in my dev version - but there's an error in there. The new mako import has a broken try except on line 20. D'you want to fix this before I raise another P/R?

**Comment by mafrosis** [comment]
Also this is another case for pylint!

**Comment by techhat** [comment]
Fixed. I guess I got lazy.

**Pull request closed without merging**
