### PR TITLE
Added verify_ssl_cert and networkid options

### PR DESCRIPTION
**Pull request by pakdel**
verify_ssl_cert can be used to disabled SSL certificate verification, which
is useful in case a self-signed certificate is used on CloudStack server.
networkid can be used to launch the server into a specific network.
Also it uses extra['password'] that is provided by latest version of libcloud.

As a result, I get to have cloud.providers and cloud.profiles files like the following:
cloud.providers 

```
mycloud:
  apikey: "Some Key"
  secretkey: "Some Key"
  host: "cloud.ops.dot"
  path: "/client/api"
  provider: cloudstack
  verify_ssl_cert: false
```

cloud.profiles

```
small:
    provider: mycloud
    image: CentOS 6 minimal
    size: Small Instance
    location: YUL01
    ssh_interface: public
    keypair: mycloud
    networkid: ab815684-880b-4c45-91ce-8e8041d15e63
```

### CODE REVIEW

**Comment by techhat** [comment]
Thanks for the contribution, @pakdel!

**Comment by pakdel** [comment]
Wow! Great! That was the fastest merge!

**Comment by pakdel** [comment]
Should I do anything to make sure that these changes will be present in next releases?

**Comment by techhat** [comment]
Nope, they're in the develop branch, so they'll be in the next release.

**Comment by pakdel** [comment]
I cloned the develop branch today, and it seems that this commit has been only merged into 0.8.9!

**Comment by techhat** [comment]
This commit shouldn't even be in 0.8.9, since it wasn't added until after that release was cut. It should only be in develop at the moment.

**Comment by techhat** [comment]
It has just barely been pointed out to me that I merged this into the 0.8.9 branch, which is incorrect. It should have been merged into develop only. @s0undt3ch will submit the correct pull req(s) to fix this.

**Comment by pakdel** [comment]
I created a pull request for develop branch: #773

**Pull request merged**
