### PR TITLE
Changes to AWS cloud config

### PR DESCRIPTION
**Pull request by mafrosis**
Hey Thomas,

So I finally raised the PR :) There's a few changes, all of which were needed to get my requirements working with AWS:
- Support for AWS regions, called 'location' in salt-cloud
- Support for availability zones, called 'availability_zones' in salt-cloud
- Can configure the username when connecting over SSH
- Can specific internal or external IPs to connect with (I run salt-cloud within the AWS data centre, so need internal)
- A small fix to only accept keys if no errors occur in create()

I also wanted to update the help files, but ran out of time. Here's my current config which should make this all make more sense:

/etc/salt/cloud:

```
    # set default config passed to all minions
    minion:
      master: salt.basketchaser.com
     
    # set the AWS login data
    AWS.id: <id>
    AWS.key: <key>
    AWS.keyname: <keyname>
    AWS.securitygroup: default
    AWS.private_key: /root/key.pem
    AWS.ssh_username: ubuntu
     
    # set default cloud provider to AWS
    provider: aws
     
    # set our default region for AWS
    AWS.location: ap-southeast-1
    AWS.availability_zone: ap-southeast-1b
    AWS.ssh_interface: private_ips
```

/etc/salt/cloud.profiles:

```
    base_aws:
      provider: aws
      image: ami-a6ca8df4
      size: Small Instance
      os: Ubuntu
      minion:
        grains:
          role: app
```

### CODE REVIEW

**Comment by thatch45** [comment]
This is fantastic @mafrosis ! This cleanly covers a lot of ground. I am going to adapt the other providers to accept concepts in similar ways, thanks!

**Comment by techhat** [comment]
@mafrosis, I'm having a hard time getting this to work, and I'm wondering if it's this patch or something else that's causing me problems. Can you look for me as redbeard2 on irc, to discuss?

**Comment by mafrosis** [comment]
@techhat I've only just seen this message... Sorry. Mostly I've been following activity in the mailing list though. Are you still having problems? Other people have also reported problems - none of which I can recreate.

**Comment by techhat** [comment]
@mafrosis, I am still having this problem. I would like to connect with you to get things figured out, for everyone's benefit. Do you mind if I email you personally? I have your address from the mailing list.

**Comment by mafrosis** [comment]
Hey Joseph, please get me on github@mafro.net to work through your issue. I see you've been doing some good work on salt-cloud! Great to see people getting behind the project.

Cheers
Matt

**Comment by inthecloud247** [comment]
cool. got this to work... the documentation needs updating, but it's working well now.

**Pull request merged**
