### PR TITLE
Include cli options into loaded config dictionary.

### PR DESCRIPTION
**Pull request by s0undt3ch**
The merge with cli mix in, only merges option keys which exist in both places, cli options and loaded config. Since neither `profile` not `parallel` existed in any of the default config dictionary, not the loaded config files, that info was not getting included.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@techhat is this enough?

**Comment by s0undt3ch** [comment]
This fix was not the issue.

**Comment by s0undt3ch** [comment]
Ok, see if this solves our issues.

**Comment by techhat** [comment]
Looks much better. Thanks, @s0undt3ch!

**Pull request merged**
