### PR TITLE
extended drivers

### PR DESCRIPTION
**Pull request by rszabo50**

### CODE REVIEW

**Comment by techhat** [comment]
Hi @rszabo50. Sorry to take so long to respond on this. I've put a lot of thought into this, and discussed it with @thatch45, and we've decided to start moving away from libcloud-based drivers. I think that libcloud has been a great project to work with, and I begrudge them nothing, but I also think that we're going in a direction that is incompatible with them.

I'll get started on a direct-API version of the JoyEnt driver, but I won't be hurt if somebody beats me to it. My version will be based on the EC2 and Parallels drivers.

**Comment by rszabo50** [comment]
joyent will be releasing a new api in the next couple of months, so expect alot of additions.

**Comment by techhat** [comment]
Sounds good. Thanks for all your hard work, @rszabo50.

**Comment by rszabo50** [comment]
@techhat, @thatch45, Quick question. I have a lot of changes in my current fork, however, if I were to redo the joyent driver using the direct-API, how would I go about removing this fork and starting a new one,  or at least undoing all the commits. I have tried a few things off the web and no luck so far.

**Comment by techhat** [comment]
@rszabo50, it looks like you've been working out of your develop branch. It's always best to work out of a feature branch. First, to throw away any changes to a file, you can just checkout the file again:

```
git checkout cloud.py
```

That's the same as doing an svn revert on the file. Once you've reset all the files and updated your develop branch to match github, make a feature branch. In this case we'll call it joyent. Assuming you are currently on the develop branch:

```
git checkout -b joyent
```

The resulting joyent branch will be identical to the develop branch. Make your changes, commit them, and then push the branch to github to make a pull req:

```
git push origin joyent
```

Once the pull req has been accepted, you'll want to checkout your develop branch again, delete your feature branch, and then update your develop branch to include the changes that were just merged upstream:

```
git checkout develop
git branch -D joyent
git fetch upstream
git pull upstream develop
```

Unless you've manually set it up, you won't have an upstream repo set up, and those last two lines will fail. In order to set it up, run:

```
git remote add upstream https://github.com/saltstack/salt-cloud.git
```

Let me know if you encounter any issues.

**Pull request closed without merging**
