### PR TITLE
added Archlinux PKGBUILD's:

### PR DESCRIPTION
**Pull request by aboe76**
- PKGBUILD-git:
  - pkgver() function from pacman 4.1 better pkg version
  - vcs function from pacman 4.1
- PKGBUILD
  - just snatch from aur.archlinux.com

### CODE REVIEW

**Comment by techhat** [comment]
@aboe76 you've been on fire with these Arch packages! I assume you've already coordinated these with @cedwards?

**Comment by aboe76** [comment]
yes I've mailed the pkgbuild to cedwards, and spoke yesterday on irc about them.
but I thought the packages he made in aur aren't in the repo...
So I uploaded them...

**Comment by aboe76** [comment]
tested all packages on my own machine. they build and run
and give a much better version number

```
local/salt-api-git v0.8.0.21.ge7e9dba-1
    Salt API is used to expose the fundamental aspects of Salt control to external sources.
local/salt-cloud-git v0.8.8.11.g10f7532-1
    Salt Cloud is a generic cloud provisioning tool
local/salt-git v0.14.0.506.g0765bc1-1
    A remote execution and communication system built on zeromq
```

**Comment by techhat** [comment]
You're the man, @aboe76!

**Pull request merged**
