### PR TITLE
Recommend reactor as method to initiate provisioning

### PR DESCRIPTION
**Pull request by akoumjian**
Since the startup_action config seems buggy at best, it made more sense to use salt's Reactor system as a way to provisioning a newly setup minion.

### CODE REVIEW

**Comment by thatch45** [comment]
Since we merged in salt-cloud to salt itself we need to get these docs in there as well

**Comment by akoumjian** [comment]
_is so out of the loop, proceeds to watch the past 10 salt airs_

**Comment by thatch45** [comment]
:)

**Comment by inthecloud247** [comment]
lol

**Pull request merged**
