### PR TITLE
Ported block_device_mappings to ec2 provider

### PR DESCRIPTION
**Pull request by clintonb**
This functionality (which allows for ephemeral storage setup) was previously only available in the AWS provider. Documentation has also been updated to prevent confusion when setting up block devices on unsupported instance types.

 Fixes #845

### CODE REVIEW

**Comment by clintonb** [comment]
Let me know if there are tests I need to update. I didn't see any in /tests.

**Comment by techhat** [comment]
@clintonb, just a note before I review this, it looks like your commit is showing up as a ghost commit. This can happen when the email addressed that it was committed under isn't registered with Github. I can still merge it, but until that address is registered, Github won't give you credit.

**Comment by clintonb** [comment]
@techhat Thanks. My profile is now up to date.

**Comment by techhat** [comment]
@clintonb looks good, both the profile and the code. Thanks for doing this!

**Pull request merged**
