### PR TITLE
added mako support to salt-cloud map files.

### PR DESCRIPTION
**Pull request by inthecloud247**
if mako is installed, salt-cloud will take advantage of it by default and try to render map files as mako first and then output as yaml.

should probably extend to work with a config file option renderer='mako'. wanted to submit this before heading off for the day...

### CODE REVIEW

**Comment by techhat** [comment]
Looks pretty straightforward. Thanks @ydavid365!

**Comment by thatch45** [comment]
Woah, we should totally bootstrap the render system for this, not piece meal in random template languages

**Comment by inthecloud247** [comment]
agreed... :-)

Would be a good idea to get the regular salt render system working here... had to just get mako working for now.

Also want to get basic pillar functionality in salt-cloud. but at least with mako now installed I can hack pillar support in by loading the pillar files using pyyaml... :-)

**Comment by thatch45** [comment]
What is the application you see for pillar here?

**Comment by inthecloud247** [comment]
I want to have pillars as the central 'source of truth' for any global data for my salt/salt-cloud cluster. So my nodes should be defined in pillars and then loaded into salt-cloud. I was able to hack this to work using mako code in my salt-cloud .map file. But it's not super robust, and ideally it should use the same shared salt template processing code. 

Here's my use case... I want to have a staging environment that I can easily bring up and down at will to test/validate our code and salt configuration.

By adding mako template code to our .map file, and by hacking in the ability to load pillar data into salt-cloud, I was able to easily build a staging environment in salt-cloud with the following machines:

#api machines
apple-staging.mydomain.com
banana-staging.mydomain.com
cherry-staging.mydomain.com
date-staging.mydomain.com

#load balancer machines
agnon-staging.mydomain.com
beckett-staging.mydomain.com

## In a servers.sls pillar file in pillar/staging/servers.sls

domain: staging.mydomain.com
environment: staging

api:
  role: 'api'
  size: 'small'
  tenant: 'single'
  dns: 'dynamic'
  instances:
    - {number: 2, provider: 'aws', region: 'west-2b'}
    - {number: 2, provider: 'aws', region: 'west-2c'}

lb:
  role: 'lb'
  size: 'small'
  tenant: 'single'
  dns: 'static'
  instances: 
    - {number: 1, provider: 'aws', region: 'west-2b'}
    - {number: 1, provider: 'aws', region: 'west-2c'}

lb_static_ips:
- 192.168.1.12
- 192.168.1.13

#and in a shared pillar: /pillar/servernamelists.sls

api_names:
- apple
- banana
- cherry
- date
- etrog

lb_names:
- agnon
- beckett
- camus
- deledda
- elytis

**Comment by techhat** [comment]
@ydavid365, I'm not sure if I've pointed this to you yet or not, but you'll want to take a look at #220, which I hope to get done next week, after the 0.8.4 release.

**Comment by inthecloud247** [comment]
@techhat that's really cool. Didn't know about that. seems like it would cover my use case really well... :-)

**Pull request merged**
