### PR TITLE
fix typo in networkids

### PR DESCRIPTION
**Pull request by sebgoa**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@whiteinge ping...

**Comment by sebgoa** [comment]
@whiteinge yeah, I made a mistake, you need to add the other commit to the pull request

**Comment by s0undt3ch** [comment]
huh?

**Comment by sebgoa** [comment]
was 7a02c46 also merged ?

**Comment by s0undt3ch** [comment]
It was :smile:

**Comment by sebgoa** [comment]
thanks. My mind does not work well with pr for some reason...I always get confused. thanks for the merge

**Pull request merged**
