### PR TITLE
Allow setting `delvol_on_destroy` for **all** EC2 VMs. PEP-8.

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by techhat** [comment]
Be aware that in 0.8.7, we're switching xml_to_dict over to salt.utils.xmlutil.

**Comment by s0undt3ch** [comment]
Hmm, and the implications of that regarding these changes?

**Comment by techhat** [comment]
Just that the _xml_to_dict function in here will disappear within the next month anyway.

**Comment by s0undt3ch** [comment]
Ah :smile: it was just a formatting change.

**Pull request merged**
