### PR TITLE
Add the ability to specify grains and other conf in the cloud.map

### PR DESCRIPTION
**Pull request by techhat**
Sample map file might look like:

gogrid_512:
    - techhat1:
        master: salt
        grains:
            omelet: du fromage
    - techhat2:
        master: salt
        grains:
            omelet: souffle

### CODE REVIEW

**Comment by techhat** [comment]
Bah... my YAML whitespace got stripped. But you get the idea.

**Comment by techhat** [comment]
Also fixes a bug I introduced earlier today, requiring a map file to be specified.

**Comment by dangarthwaite** [comment]
Breaks with my simplistic map:

```
aws_small:
  - server1


    Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/local/lib/python2.6/dist-packages/saltcloud/cli.py", line 233, in run
    mapper.run_map()
  File "/usr/local/lib/python2.6/dist-packages/saltcloud/cloud.py", line 274, in run_map
    tvm['map_grains'] = miniondict[name]['grains'] 
TypeError: string indices must be integers, not str
```

**Comment by thatch45** [comment]
Good catch, we will get this fixed

**Comment by thatch45** [comment]
Fixed:
355c319e8e8994fe572f4ab8c148a4b8962e0402

**Pull request merged**
